config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'events#index'
  resources :events do
    get 'copy', action: :new
    post 'cancel', on: :member, action: :cancel
  end
  resources :tickets

  resources :participants do
    post 'kick_out', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participants, dependent: :destroy
  has_many :event_owners, dependent: :destroy
  has_many :users, through: :participants
  has_many :owners, through: :event_owners, source: :user
  has_many :tickets, dependent: :destroy
  accepts_nested_attributes_for :tickets, allow_destroy: true
end

app/models/event_owner.rb
class EventOwner < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  has_many :participants
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :participants, dependent: :destroy
  has_many :event_owners, dependent: :destroy
  has_many :events, through: :participants
  has_many :own_events, through: :event_owners, source: :event

  def participate!(event, ticket, comment)
    participant = participants.find_or_initialize_by(event_id: event.id, ticket_id: ticket.id)
    participant.comment = comment
    participant.canceled_at = nil
    participant.save!
  end

  def participated?(event)
    participant = participants.find_by(event_id: event.id)
    participant.present? && !participant.canceled_at?
  end

  def cancel!(event)
    participant = participants.find_by(event_id: event.id)
    participant.destroy!
  end

  def owner?(event)
    event_owners.find_by(event_id: event.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name profile avatar avatar_cache)

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :destroy]
  def index
    @events = Event.all
    @event = Event.new
    3.times.each { @event.tickets.build }

    # sample for gon
    gon.user_name = current_user.try!(:name) || '名無しさん'
  end

  def show
  end

  def new
    @event = Event.new
    @event.tickets.build
    if event_id = params[:event_id]
      @copy = Event.find(event_id)
    end
  end

  def create
    @event = Event.new(events_params)
    if @event.save
      current_user.event_owners.create(event_id: @event.id)
      redirect_to root_path, notice: "イベントを作成しました！"
    else
      render :new
    end
  end

  def cancel
    event = Event.find(params[:id])
    event.canceled_at = Time.current
    if event.save
      redirect_to event, notice: "イベントを中止しました！"
    else
      redirect_to event, notice: "イベントが中止できませんでした！"
    end
  end


  def destroy
    if @event.destroy
      redirect_to root_path, notice: "イベントを削除しました！"
    else
      redirect_to root_path, notice: "イベントが削除できませんでした！"
    end
  end

  private
    def events_params
      params.require(:event).permit(
        :title, :description, :content, :start_time, :end_time, :canceled_at, :participant_public_flg,
        tickets_attributes: [:name, :price, :capacity]
    )
    end

    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_user!

  def create
    event = Event.find(params[:participant][:event_id])
    ticket = Ticket.find(params[:participant][:ticket_id])
    comment = params[:participant][:comment]
    current_user.participate!(event, ticket, comment)
    redirect_to event_path(event), notice: "参加しました！"
  end

  def destroy
    event = Participant.find(params[:id]).event
    current_user.cancel!(event)
    redirect_to event_path(event), notice: "キャンセルしました！"
  end

  def kick_out
    participant = Participant.find(params[:id])
    participant.kicked_out_at = Time.current
    if participant.save
      flash[:notice] = '参加者を追い出しました'
    else
      flash[:notice] = '参加者を追いだせませんでした'
    end
    redirect_to event_path(participant.event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/events/_form.html.erb
<%= form_for event do |f| %>
  <h3>イベントについて</h3>
  <div>
    <%= f.label :タイトル %>
    <%= f.text_field :title, value: @copy&.title %>

    <%= f.label :概要 %>
    <%= f.text_field :description, value: @copy&.description %>
    <br>
    <%= f.label :内容 %>
    <%= f.text_area :content, value: @copy&.content %>
    <br>
    <%= f.label :開始時間 %>
    <%= f.datetime_local_field :start_time %>
    <%= f.label :終了時間 %>
    <%= f.datetime_local_field :end_time %>
  </div>
  <h3>チケット</h3>
  <div>
    <%= f.fields_for :tickets do |tf| %>
      <%= render 'tickets_form', tf: tf %>
      <%=  %>
    <% end %>
  </div>
  <div>
    <%= f.label :参加者リストを公開する %>
    <%= f.check_box :participant_public_flg %> (※イベントページに参加者リストを表示する場合にはチェックしてください。)
  </div>

  <%= f.submit '投稿' %>
<% end %>

app/views/events/_tickets_form.html.erb
<%= tf.label :チケット名 %>
<%= tf.text_field :name %>

<%= tf.label :参加費 %>
<%= tf.number_field :price %>

<%= tf.label :枚数 %>
<%= tf.number_field :capacity %>
<br>

app/views/events/index.html.erb
<h2>イベントを作成する</h2>
<%= render 'form', event: @event %>

<h2>イベント一覧</h2>
<table>
  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.title, event_path(event) %></td>
      <td>（<%= event.description %>）</td>
      <td><%= link_to '削除', event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete?" }%></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h2>イベントを作成する</h2>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<% if user_signed_in? %>
  <p>あなたはこのイベントの管理者<%= current_user.owner?(@event) ? "です" : "ではありません" %></p>
  <% if @event.canceled_at? %>
    <p style="color:red;">このイベントは中止となりました</p>
  <% else%>
    <%= button_to "イベントを中止する", cancel_event_path(@event),
                  data: { confirm: "この操作は取り消せません。本当にイベントを中止しますか？" } %>
  <% end %>
<% end %>
<h3>イベント情報</h3>
<table>
  <tr>
    <td>イベント名</td>
    <td><%= @event.title %></td>
  </tr>
  <tr>
    <td>概要</td>
    <td><%= @event.description %></td>
  </tr>
  <tr>
    <td>内容</td>
    <td><%= @event.content %></td>
  </tr>
  <tr>
    <td>開始時間</td>
    <td><%= @event.start_time %></td>
  </tr>
  <tr>
    <td>終了時間</td>
    <td><%= @event.end_time %></td>
  </tr>
</table>

<% unless @event.canceled_at? %>
  <% if user_signed_in? %>
    <% if current_user.participated?(@event) %>
      <%= form_for(current_user.participants.find_by(event_id: @event.id), html: { method: :delete }) do |f| %>
        <%= f.submit "参加をキャンセルする" %>
      <% end %>
    <% else %>
      <h3>チケットを選択</h3>
      <%= form_for(current_user.participants.build(event_id: @event.id, ticket_id: @event.tickets.first.id)) do |f| %>
        <ul>
          <% @event.tickets.each_with_index do |ticket, index| %>
            <% checked = index == 0 ? true : false %>
            <li>
              <%= f.radio_button :ticket_id, ticket.id, checked: checked %>
              チケット名：<%= ticket.name %> / 参加費：<%= "#{ticket.price}円" %> / 定員：<%= "#{ticket.capacity}人" %>
            </li>
          <% end %>
        </ul>
        <%= f.hidden_field :event_id %>
        <%= f.hidden_field :ticket_id %>
        <%= f.label :コメント %>
        <%= f.text_field :comment %>
        <br>
        <%= f.submit "参加する" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<h3>イベント主催者</h3>
<p><%= @event.owners.first.name %></p>

<h3>参加者一覧</h3>
<% if @event.participant_public_flg? %>
  <% if @event.participants.present? %>
    <table>
      <% @event.participants.each do |participant| %>
        <% unless participant.canceled_at? || participant.kicked_out_at? %>
          <tr>
            <td><%= "#{participant.user.name} (コメント:#{participant.comment})" %></td>
            <% if user_signed_in? && current_user.owner?(@event) %>
              <td><%= button_to "追い出す", kick_out_participant_path(participant) %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% end %>
<% else %>
  <p>このイベントの参加者リストは非公開です。</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Huboo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <li><%= link_to 'TOPへ', root_path %></li>
      <% if user_signed_in? %>
       <li><%= link_to "マイページ", edit_user_registration_path %></li>
       <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
       <li><%= link_to 'ログイン', new_user_session_path %></li>
       <li><%= link_to 'サインアップ', new_user_registration_path %></li>
       <% end %>
      <%= notice %>
    </header>
    <%= yield %>
    <%= javascript_pack_tag 'hello_vue' %>
  </body>
</html>